# Generated by Django 4.2.2 on 2024-08-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_alter_postmodel_slug'),
        ('ProfileApp', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cate', to='Post.category'),
        ),
    ]
